[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "hypergo"
version = "0.3.9"
description = "Project for service bus"

[tool.setuptools_scm]
